function plotHallOfFame(X1, Y1)
%PLOTHALLOFFAME(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 06-Oct-2015 07:24:07

% Create figure
figure1 = figure;
movegui(figure1,'northwest');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',16,'FontName','Times New Roman');
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-0.05 1.05]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',3);

% Create title
title('Hall of fame','FontWeight','bold','FontSize',22,'FontName','Times');

% Create xlabel
xlabel('Generation','FontWeight','demi','FontSize',18,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('Fitness','FontWeight','demi','FontSize',18,...
    'FontName','Times New Roman');

