function plotCost(X1, Y1)
%PLOTCOST(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 06-Oct-2015 12:55:51

% Create figure
figure1 = figure;
movegui(figure1,'north');

% Create axes
axes1 = axes('Parent',figure1,'YTick',[0 40 80 120 160 200 240 280 320],...
    'FontSize',16,'FontName','Times New Roman');
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 300]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',3.0);

% Create title
title('Costs of hall of fame items','FontWeight','bold','FontSize',22,...
    'FontName','Times New Roman');

% Create xlabel
xlabel('Generations','FontWeight','demi','FontSize',18,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('Cost ($)','FontWeight','demi','FontSize',18,...
    'FontName','Times New Roman');

