function plotRequirements(xvector1, ymatrix1)
%PLOTREQUIREMENTS(XVECTOR1, YMATRIX1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 05-Oct-2015 19:00:40

% Create figure
figure1 = figure;
movegui(figure1,'southwest');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'XTickLabel',{'Kilo Calories','Protein (grams)','Calcium (grams)',...
    'Iron (mg)','Vitamin A (1000 IU)','Thiamine (mg)','Riboflavin (mg)',...
    'Niacin (mg)','Ascorbic Acid (mg)'},...
    'XTick',[1 2 3 4 5 6 7 8 9],...
    'Position',[0.129479166666667 0.11 0.775 0.705850722311396],...
    'FontSize',14,'FontName','Times New Roman');

box(axes1,'on');
hold(axes1,'all');

% Create xlabel
xlabel({'','Nutritional Requirements'},'FontWeight','demi','FontSize',18,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('Units of Measure','FontWeight','demi','FontSize',18,...
    'FontName','Times New Roman');

% Create title
title({'Nutrition obtained versus nutrition required','',''},...
    'FontWeight','bold','FontSize',22,'FontName','Times New Roman');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'LineWidth',3,'BaseValue',1,'Parent',axes1);
set(bar1(2),'FaceColor',[1 0 1],'DisplayName','Required');
set(bar1(1),'FaceColor',[0 1 1],'DisplayName','Obtained');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthOutside');
% Resize the axes in order to prevent it from shrinking.
set(axes1,'Position',[0.129479166666667 0.11 0.775 0.705850722311396]);

